# Generated by Django 6.0.8 on 2026-10-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0004_buildproject_connection_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildproject",
            name="approved_map_data",
            field=models.JSONField(
                blank=True, help_text="Snapshot of map_data and connection taken at approval", null=True
            ),
        ),
    ]
