# Generated by Django 6.0.8 on 2026-10-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("builder", "0006_unsnapshotted_approvals_to_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildproject",
            name="built_object_ids",
            field=models.JSONField(blank=True, default=dict, help_text="Ids of the objects the sandbox build created"),
        ),
    ]
