# Generated by Django 6.0.8 on 2026-10-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boon',
            name='creditor_confirmed',
            field=models.BooleanField(default=False, help_text='The creditor has confirmed the called-in favor was done'),
        ),
        migrations.AddField(
            model_name='boon',
            name='debtor_confirmed',
            field=models.BooleanField(default=False, help_text='The debtor has confirmed the called-in favor was done'),
        ),
        migrations.DeleteModel(
            name='BoonLedger',
        ),
    ]
