# Generated by Django 6.0.8 on 2026-10-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boons', '0002_fulfilment_confirmations_drop_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='boon',
            name='dispute_upheld',
            field=models.BooleanField(default=False, help_text="A dispute was rejected and the boon upheld; it can't be disputed again"),
        ),
        migrations.AddField(
            model_name='boon',
            name='disputed_from',
            field=models.CharField(blank=True, help_text='Status the boon had when it was disputed', max_length=20),
        ),
    ]
