# Generated by Django 6.0.8 on 2026-10-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='read_perm',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='write_perm',
        ),
    ]
