# Generated by Django 6.0.8 on 2026-10-02 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_characterbio_status_background'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbio',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account that owns this character', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_bios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterbio',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the last review decision was made', null=True),
        ),
        migrations.AddField(
            model_name='characterbio',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff account that made the last review decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_character_bios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='characterbio',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='submitted', help_text='Current approval status', max_length=20),
        ),
    ]
