# Generated by Django 6.0.8 on 2026-10-02 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_owners(apps, schema_editor):
    """Applications made before this migration recorded the owner only as the
    character's db_account; copy it into CharacterBio.account. A leftover
    'draft' status becomes 'submitted'."""
    CharacterBio = apps.get_model("traits", "CharacterBio")
    for bio in CharacterBio.objects.select_related("character").filter(account__isnull=True):
        if bio.character.db_account_id:
            bio.account_id = bio.character.db_account_id
            bio.save(update_fields=["account"])
    CharacterBio.objects.filter(status="draft").update(status="submitted")


# Hand-edited after `evennia makemigrations traits`: the traitvalue
# unique_together change is moved before the removal of its field (the
# generated order fails with KeyError 'trait'), and backfill_owners added.
class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_characterbio_status_background'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencetransaction',
            name='related_power',
        ),
        migrations.AlterUniqueTogether(
            name='charactertrait',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='charactertrait',
            name='character',
        ),
        migrations.RemoveField(
            model_name='charactertrait',
            name='trait',
        ),
        migrations.RemoveField(
            model_name='experiencetransaction',
            name='related_trait',
        ),
        migrations.AlterUniqueTogether(
            name='disciplinepower',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='disciplinepower',
            name='amalgam_discipline',
        ),
        migrations.RemoveField(
            model_name='disciplinepower',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='experiencetransaction',
            name='character',
        ),
        migrations.AlterUniqueTogether(
            name='trait',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trait',
            name='category',
        ),
        migrations.RemoveField(
            model_name='traitprerequisite',
            name='trait',
        ),
        migrations.RemoveField(
            model_name='traitprerequisite',
            name='required_trait',
        ),
        migrations.AlterUniqueTogether(
            name='traitvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='traitvalue',
            name='trait',
        ),
        migrations.RemoveField(
            model_name='characterbio',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='characterbio',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='characterbio',
            name='clan',
        ),
        migrations.RemoveField(
            model_name='characterbio',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='characterbio',
            name='predator_type',
        ),
        migrations.RemoveField(
            model_name='characterbio',
            name='splat',
        ),
        migrations.AddField(
            model_name='characterbio',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account that owns this character', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_bios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterbio',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the last review decision was made', null=True),
        ),
        migrations.AddField(
            model_name='characterbio',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Staff account that made the last review decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_character_bios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='characterbio',
            name='submission',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(backfill_owners, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='characterbio',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='submitted', help_text='Current approval status', max_length=20),
        ),
        migrations.DeleteModel(
            name='CharacterPower',
        ),
        migrations.DeleteModel(
            name='CharacterTrait',
        ),
        migrations.DeleteModel(
            name='DisciplinePower',
        ),
        migrations.DeleteModel(
            name='ExperienceTransaction',
        ),
        migrations.DeleteModel(
            name='TraitCategory',
        ),
        migrations.DeleteModel(
            name='TraitPrerequisite',
        ),
        migrations.DeleteModel(
            name='Trait',
        ),
        migrations.DeleteModel(
            name='TraitValue',
        ),
    ]
